version: "3.6"

volumes:
  postgres:

services:
  postgres:
    image: postgres:13.4
    pull_policy: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 54311:5432

  redis:
    image: redis

  web-app-dev-env:
    image: go-image-web-app
    pull_policy: always
    stdin_open: true 
    tty: true 
    volumes:
      - ../:/opt/workspace/